### PR TITLE
MVP Rust Script

### PR DESCRIPTION
**Pull request by sevanspowell**
- Rust script to replicate Haskell implementation. The only difference I can
  observe is that it does not support extended staking keys, and I haven't handled slot numbers either.
- Does not support extended staking keys, and it should to have parity with the
  Haskell implementation.
  - I don't think the underlying libraries support StakeExtendedPublicKeys.
- ~Does not properly support delegations - delegations need to be handled when validating registrations~
  - Now handled.
- Does not do proper error-handling.
- I've never written Rust, and wasn't concerned about best practices or memory
  semantics, so it needs review by a proper Rust engineer.
- Does not handle parsing arguments from the command line like slot number of database config.
- Does not handle slot number restriction.

Sorry, I didn't realize that you'd already started this, until I went to upload the repository and chose the same name. Thankfully we've worked on complementing parts, you've already done the work of parsing command line arguments, and I've left that out.

### CODE REVIEW

**Comment by sevanspowell** [comment]
I'll clean it up a bit on Monday, so leaving as draft.

I'll let you make decisions about architecture and the like, I'll just leave it as a single file.

Past Monday I won't be available for more clarification, so please feel free to steal liberally.

**Comment by minikin** [comment]
@sevanspowell Thank you!

@cameron1024 please, have a look.

**Comment by cameron1024** [comment]
This looks good, I was  having some trouble grokking the haskell side, but this is super helpful, thanks! :grin:

**Comment by sevanspowell** [comment]
So I've done a bit of manual comparison (on mainnet) between the output of:
 - `voting-tools`, and
 - `voting-tools-rs`.

They're almost exactly the same aside from 7 registrations which use stake extended public keys. As I mentioned in the original PR description, stake extended public keys aren't supported yet.

This is good news! So as it stands, this rust script has parity with the Haskell implementation.

**Comment by cameron1024** [comment]
Closing this. Thanks for all the help, really helped guide the current implementation!

**Pull request closed without merging**
